version: '3'

services:

  etcd1:
    image: quay.io/coreos/etcd
    command: [
      "etcd", 
      "--name", "node1", 
      "--data-dir", "/etcd-data",
      "--initial-advertise-peer-urls", "http://etcd1:2380", 
      "--listen-peer-urls", "http://0.0.0.0:2380", 
      "--listen-client-urls", "http://0.0.0.0:2381", 
      "--advertise-client-urls", "http://etcd1:2381", 
      "--initial-cluster-token", "etcd-cluster", 
      "--initial-cluster", "node1=http://etcd1:2380,node2=http://etcd2:2380,node3=http://etcd3:2380,node4=http://etcd4:2380,node5=http://etcd5:2380", 
      "--initial-cluster-state", "new"
    ]
    container_name: etcd1
    volumes: 
          - ./db/etcd1:/etcd-data
    ports:
      - '2381:2381'

  etcd2:
    image: quay.io/coreos/etcd
    command: [
      "etcd", 
      "--name", "node2", 
      "--data-dir", "/etcd-data",
      "--initial-advertise-peer-urls", "http://etcd2:2380", 
      "--listen-peer-urls", "http://0.0.0.0:2380", 
      "--listen-client-urls", "http://0.0.0.0:2382", 
      "--advertise-client-urls", "http://etcd2:2382", 
      "--initial-cluster-token", "etcd-cluster", 
      "--initial-cluster", "node1=http://etcd1:2380,node2=http://etcd2:2380,node3=http://etcd3:2380,node4=http://etcd4:2380,node5=http://etcd5:2380", 
      "--initial-cluster-state", "new"
    ]
    container_name: etcd2
    volumes: 
          - ./db/etcd2:/etcd-data
    ports:
      - '2382:2382'
  
  etcd3:
    image: quay.io/coreos/etcd
    command: [
      "etcd", 
      "--name", "node3", 
      "--data-dir", "/etcd-data",
      "--initial-advertise-peer-urls", "http://etcd3:2380", 
      "--listen-peer-urls", "http://0.0.0.0:2380", 
      "--listen-client-urls", "http://0.0.0.0:2383", 
      "--advertise-client-urls", "http://etcd3:2383", 
      "--initial-cluster-token", "etcd-cluster", 
      "--initial-cluster", "node1=http://etcd1:2380,node2=http://etcd2:2380,node3=http://etcd3:2380,node4=http://etcd4:2380,node5=http://etcd5:2380", 
      "--initial-cluster-state", "new"
    ]
    container_name: etcd3
    volumes: 
          - ./db/etcd3:/etcd-data
    ports:
      - '2383:2383'
  
  etcd4:
    image: quay.io/coreos/etcd
    command: [
      "etcd", 
      "--name", "node4", 
      "--data-dir", "/etcd-data",
      "--initial-advertise-peer-urls", "http://etcd4:2380", 
      "--listen-peer-urls", "http://0.0.0.0:2380", 
      "--listen-client-urls", "http://0.0.0.0:2384", 
      "--advertise-client-urls", "http://etcd4:2384",  
      "--initial-cluster-token", "etcd-cluster", 
      "--initial-cluster", "node1=http://etcd1:2380,node2=http://etcd2:2380,node3=http://etcd3:2380,node4=http://etcd4:2380,node5=http://etcd5:2380", 
      "--initial-cluster-state", "new"
    ]
    container_name: etcd4
    volumes: 
          - ./db/etcd4:/etcd-data
    ports:
      - '2384:2384'
  
  etcd5:
    image: quay.io/coreos/etcd
    command: [
      "etcd", 
      "--name", "node5", 
      "--data-dir", "/etcd-data",
      "--initial-advertise-peer-urls", "http://etcd5:2380", 
      "--listen-peer-urls", "http://0.0.0.0:2380", 
      "--listen-client-urls", "http://0.0.0.0:2385", 
      "--advertise-client-urls", "http://etcd5:2385", 
      "--initial-cluster-token", "etcd-cluster", 
      "--initial-cluster", "node1=http://etcd1:2380,node2=http://etcd2:2380,node3=http://etcd3:2380,node4=http://etcd4:2380,node5=http://etcd5:2380", 
      "--initial-cluster-state", "new"
    ]
    container_name: etcd5
    volumes: 
          - ./db/etcd5:/etcd-data
    ports:
      - '2385:2385'